# Generated by Django 3.0.8 on 2020-07-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaidVacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('employer', models.TextField()),
                ('employer_logo', models.TextField()),
                ('city', models.TextField()),
                ('tags', models.TextField()),
                ('url', models.TextField()),
                ('date', models.TextField()),
                ('color', models.TextField()),
            ],
        ),
    ]
