# Generated by Django 3.0.8 on 2020-08-04 13:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stdapp', '0002_auto_20200723_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='paidvacancy',
            name='city',
            field=models.TextField(default='lol'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paidvacancy',
            name='date',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paidvacancy',
            name='employer',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paidvacancy',
            name='employer_logo',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paidvacancy',
            name='name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paidvacancy',
            name='tags',
            field=models.TextField(default='dfdsfsf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paidvacancy',
            name='url',
            field=models.TextField(default='fdsfdasf'),
            preserve_default=False,
        ),
    ]
