# Generated by Django 3.0.8 on 2020-08-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdapp', '0004_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='amount',
            field=models.TextField(default=150.0),
            preserve_default=False,
        ),
    ]
