# Generated by Django 3.0.8 on 2020-07-23 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nocsokru_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paidvacancy',
            name='city',
        ),
        migrations.RemoveField(
            model_name='paidvacancy',
            name='date',
        ),
        migrations.RemoveField(
            model_name='paidvacancy',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='paidvacancy',
            name='employer_logo',
        ),
        migrations.RemoveField(
            model_name='paidvacancy',
            name='name',
        ),
        migrations.RemoveField(
            model_name='paidvacancy',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='paidvacancy',
            name='url',
        ),
    ]
